### ISSUE TITLE
Defining what a session is may help new readers

### ISSUE THREAD

**Issue by kierans** [RedCrewOS/open-qr-standard#7]
Having read through the standard a couple of times, it's not clear what a "session" is. Specifically, what comprises a session, and what does it mean to claim a session. If I was implementing a Code Producer I'm not clear on what I would have to record in my system.

**Comment by JamesMBligh** [comment]
Thanks I'll add this in Kieran

**Comment by JamesMBligh** [comment]
Resolved in v1.0.0
